import jsPDF from "jspdf";

const valueOrDash = (value) => (value === null || value === undefined || value === "" ? "-" : String(value));

export const downloadReceiptPdf = (receipt) => {
  const doc = new jsPDF();
  const studentName = [receipt?.first_name, receipt?.middle_name, receipt?.last_name]
    .filter(Boolean)
    .join(" ");

  doc.setFontSize(16);
  doc.text("SSG Payment Receipt", 14, 18);
  doc.setFontSize(10);
  doc.text("Supreme Student Government", 14, 24);

  doc.setLineWidth(0.3);
  doc.line(14, 28, 196, 28);

  const lines = [
    ["Receipt Number", valueOrDash(receipt?.receipt_number)],
    ["Student Name", valueOrDash(studentName)],
    ["Student ID Number", valueOrDash(receipt?.student_number)],
    ["Fee Name", valueOrDash(receipt?.fee_name)],
    ["Amount", `PHP ${Number(receipt?.amount || 0).toLocaleString()}`],
    [
      "Paid At",
      receipt?.paid_at ? new Date(receipt.paid_at).toLocaleString() : "-",
    ],
    ["PayMongo Reference", valueOrDash(receipt?.paymongo_reference)],
    ["Payment Method", valueOrDash(receipt?.payment_method)],
    ["Approved By", valueOrDash(receipt?.approved_by)],
    ["Payment Status", valueOrDash(receipt?.payment_status)],
    ["Officer review", valueOrDash(receipt?.officer_status)],
  ];

  let y = 38;
  lines.forEach(([label, value]) => {
    doc.setFontSize(10);
    doc.setFont(undefined, "bold");
    doc.text(`${label}:`, 14, y);
    doc.setFont(undefined, "normal");
    doc.text(value, 62, y);
    y += 8;
  });

  doc.setLineWidth(0.3);
  doc.line(14, y + 4, 196, y + 4);
  doc.setFontSize(9);
  doc.text("Generated by SSG Payment System", 14, y + 11);
  doc.text("This document is system-generated.", 14, y + 16);

  doc.save(`receipt-${valueOrDash(receipt?.receipt_number || receipt?.payment_id)}.pdf`);
};
